"""
Initialization file for the scheduler module of the Electricity Market Price Forecasting System.
Exports key components and functions for scheduling and executing the daily forecast generation process at 7 AM CST.
"""

__version__ = "1.0.0"

from .exceptions import (
    SchedulerError,
    JobSchedulingError,
    JobExecutionError,
    JobTimeoutError,
    JobRegistryError,
    MonitoringError,
    ScheduleConfigurationError,
    SchedulerInitializationError,
)
from .scheduler_logging import (
    logger,
    log_scheduler_startup,
    log_scheduler_shutdown,
    log_scheduler_error,
    log_job_execution_start,
    log_job_execution_completion,
    log_job_execution_failure,
)
from .job_registry import (
    register_job,
    get_job,
    update_job_status,
    get_jobs_by_status,
    get_jobs_by_type,
    get_all_jobs,
    JOB_STATUS_PENDING,
    JOB_STATUS_RUNNING,
    JOB_STATUS_COMPLETED,
    JOB_STATUS_FAILED,
    JOB_STATUS_TIMEOUT,
)
from .execution_monitor import (
    start_job_monitoring,
    stop_job_monitoring,
    get_monitored_jobs,
    DEFAULT_TIMEOUT_SECONDS,
)
from .forecast_scheduler import (
    initialize_scheduler,
    start_scheduler,
    stop_scheduler,
    is_scheduler_running,
    schedule_forecast_job,
    execute_forecast_job,
    schedule_one_time_forecast,
    run_forecast_now,
    get_next_run_time,
    get_scheduler_status,
    ForecastScheduler,
    JOB_TYPE_FORECAST,
)

__all__ = [
    "SchedulerError",
    "JobSchedulingError",
    "JobExecutionError",
    "JobTimeoutError",
    "JobRegistryError",
    "MonitoringError",
    "ScheduleConfigurationError",
    "SchedulerInitializationError",
    "logger",
    "log_scheduler_startup",
    "log_scheduler_shutdown",
    "log_scheduler_error",
    "log_job_execution_start",
    "log_job_execution_completion",
    "log_job_execution_failure",
    "register_job",
    "get_job",
    "update_job_status",
    "get_jobs_by_status",
    "get_jobs_by_type",
    "get_all_jobs",
    "JOB_STATUS_PENDING",
    "JOB_STATUS_RUNNING",
    "JOB_STATUS_COMPLETED",
    "JOB_STATUS_FAILED",
    "JOB_STATUS_TIMEOUT",
    "start_job_monitoring",
    "stop_job_monitoring",
    "get_monitored_jobs",
    "DEFAULT_TIMEOUT_SECONDS",
    "initialize_scheduler",
    "start_scheduler",
    "stop_scheduler",
    "is_scheduler_running",
    "schedule_forecast_job",
    "execute_forecast_job",
    "schedule_one_time_forecast",
    "run_forecast_now",
    "get_next_run_time",
    "get_scheduler_status",
    "ForecastScheduler",
    "JOB_TYPE_FORECAST",
    "__version__",
]