# GitHub Dependabot configuration file for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies for backend
  - package-ecosystem: "pip"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    allow:
      dependency-type: "all"
    assignees:
      - "data-science-lead"
    labels:
      - "dependencies"
      - "backend"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"

  # Python dependencies for web components
  - package-ecosystem: "pip"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    allow:
      dependency-type: "all"
    assignees:
      - "web-development-lead"
    labels:
      - "dependencies"
      - "web"
      - "python"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"

  # JavaScript dependencies for web components
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    allow:
      dependency-type: "all"
    assignees:
      - "web-development-lead"
    labels:
      - "dependencies"
      - "web"
      - "javascript"
    open-pull-requests-limit: 10
    versioning-strategy: "auto"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    assignees:
      - "devops-lead"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    versioning-strategy: "auto"

  # Docker dependencies for backend
  - package-ecosystem: "docker"
    directory: "/src/backend"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    assignees:
      - "devops-lead"
    labels:
      - "dependencies"
      - "docker"
      - "backend"
    open-pull-requests-limit: 5

  # Docker dependencies for web components
  - package-ecosystem: "docker"
    directory: "/src/web"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    assignees:
      - "devops-lead"
    labels:
      - "dependencies"
      - "docker"
      - "web"
    open-pull-requests-limit: 5