version: '3.8'

services:
  visualization-service:
    description: Dash-based visualization service for electricity market price forecasts
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-True}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8050
      - API_BASE_URL=${API_BASE_URL:-http://forecasting-service:8000/api} # Library version: requests 2.28.0+
      - FORECAST_API_TIMEOUT=${FORECAST_API_TIMEOUT:-30}
      - DASHBOARD_REFRESH_INTERVAL_SECONDS=${DASHBOARD_REFRESH_INTERVAL_SECONDS:-300} # Library version: Dash 2.9.0+
      - ENABLE_RESPONSIVE_UI=${ENABLE_RESPONSIVE_UI:-True} # Library version: Dash 2.9.0+
      - CACHE_ENABLED=${CACHE_ENABLED:-True} # Library version: diskcache 5.4.0+
      - CACHE_TIMEOUT=${CACHE_TIMEOUT:-300} # Library version: diskcache 5.4.0+
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env
    volumes:
      - visualization-cache:/app/cache
      - visualization-logs:/app/logs
    ports:
      - "8050:8050"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - forecast-network
    depends_on:
      forecasting-service:
        condition: service_healthy

volumes:
  visualization-cache:
    description: Persistent storage for visualization cache data
    driver: local
  visualization-logs:
    description: Persistent storage for visualization logs
    driver: local

networks:
  forecast-network:
    description: Shared network for forecast services communication
    driver: bridge
    external: true